config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'

  resources :charges
  resources :users
  resources :conversations do
  resources :messages
  end

  get '/login'      => 'session#new', :as => "login"
  post '/login'     => 'session#create'
  delete '/logout'  => 'session#destroy', :as => "logout"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  firstname       :string
#  lastname        :string
#  email           :text
#  dob             :date
#  image           :text
#  admin           :boolean          default(FALSE)
#  password_digest :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_many :conversations, :foreign_key => :sender_id
  has_many :charges, :foreign_key => :user_id
  has_secure_password
  has_many :messages, :through => :conversations
  validates :firstname, presence: true,length: { minimum: 2 }
  validates :lastname, presence: true,length: { minimum: 2 }
  validates :email, presence: true, uniqueness: true, format: { with: /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i,
    message: "Now a valid email address" },length: { minimum: 5 }


def self.search(search)
  where("doctor_speciality LIKE ?", "%#{search}%")
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #  username        :string
  #  firstname       :string
  #  lastname        :string
  #  email           :text
  #  dob             :date
  #  image           :text
  #  password_digest :text


  def index
    @users=User.all
    @all_doctors=@users.where(:doctor=>true)
    if params[:search]
      @search_text="%#{params[:search]}%"
      @doctors = @all_doctors.where("lower(doctor_speciality) LIKE ?", @search_text.downcase).order("created_at DESC")
    else
      @doctors = @all_doctors.all.order('created_at DESC')
    end
  end

  def search

  end

  def edit
    @user = User.find params[:id]
  end

  def show
    @is_charged = false
    @user=User.find params[:id]
    if logged_in?
      @conversations=Conversation.all
      @payment_entry = Charge.find_by(:doctor => @user.id , :user =>current_user.id)
      if @payment_entry.present?
        @is_charged = @payment_entry.payment_charged?
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create!(user_params)
    if params[:file].present?
        # Then call Cloudinary's upload method, passing in the file in params
        req = Cloudinary::Uploader.upload(params[:file])
      # Using the public_id allows us to use Cloudinary's powerful image transformation methods.
      @user.image = req["public_id"]
    end
    if @user.save
      if @user.doctor?
        redirect_to user_path(@user)
      else
        redirect_to login_path
      end
    end
  end

  def update
    @user = User.find params[:id]
    if params[:file].present?
          # Then call Cloudinary's upload method, passing in the file in params
          req = Cloudinary::Uploader.upload(params[:file])
        # Using the public_id allows us to use Cloudinary's powerful image transformation methods.
        @user.image = req["public_id"]
    end
    # We're using update_attributes here because we don't want to make to PUT requests (.update to update the attributes in @user_params, then .save to update the image)
    @user.update_attributes(user_params)
    @user.save
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    redirect_to users_path

  end

  private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :dob, :doctor_qualifications, :doctor_speciality, :doctor_expertise, :doctor_professional_experience, :doctor_awards_recognitions, :doctor_memberships, :doctor_publications, :doctor, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_doctor_form.html.erb
<%= form_for(@user, :html => {:multipart => true }) do |f| %>
<div class="col-md-offset-2 col-md-4">
  <%= f.text_field :firstname, :placeholder => "First Name" %><br>
  <%= f.text_field :lastname, :placeholder => "Last Name"%><br>
  <%= f.email_field :email, :placeholder => "Email"  %><br>
  <%= f.text_field :doctor_speciality, :placeholder => "Speciality"  %><br>
  <%= f.password_field :password, :placeholder => "Password", :required => true %><br>
  <%= f.password_field :password_confirmation, :placeholder => "Confirm Password", :required => true %><br>
</div>
<div class="col-md-4">
  <%= f.text_field :doctor_qualifications, :placeholder => "Qualifications" %><br>
  <%= f.text_field :doctor_professional_experience, :placeholder => "Professional Experience"  %><br>
  <%= f.text_field :doctor_awards_recognitions, :placeholder => "Awards & Recognition"  %><br>
  <%= f.text_field :doctor_memberships, :placeholder => "Memberships" %><br>
  <%= f.text_field :doctor_publications, :placeholder => "Publications" %><br>
  <%= f.cl_image_upload :image, :placeholder => "Avatar"  %><br>
  <%= f.text_field :doctor, value: true, type: "hidden"  %>
</div>
<div class="row">
  <div class="col-md-offset-4 col-md-4">
    <%= f.submit "Submit",:class => "btn btn-primary btn-block btn-medium" %><br>
  </div>
</div>

<% end %>

app/views/users/_form.html.erb
<!-- #  username        :string
#  firstname       :string
#  lastname        :string
#  email           :text
#  dob             :date
#  image           :text
#  password_digest :text -->
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>

  <%= f.label :firstname %>
  <%= f.text_field :firstname %><br>

  <%= f.label :lastname %>
  <%= f.text_field :lastname %><br>

  <%= f.label :email %>
  <%= f.email_field :email %><br>

  <%= f.label :dob %>
  <%= f.date_select :dob %><br>

  <%= f.label :image %>
    <%= f.url_field :image%><br>

  <%= f.label :password %>
  <%= f.password_field :password %><br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>

  <%= f.submit "Sign up" %>
<% end %>

app/views/users/_user_form.html.erb
<!-- #  username        :string
#  firstname       :string
#  lastname        :string
#  email           :text
#  dob             :date
#  image           :text
#  password_digest :text -->

<div class="col-md-offset-4 col-md-4">
  <%= form_for @user do |f| %>
    <%= f.text_field :firstname, :placeholder => "First Name" %><br>
    <%= f.text_field :lastname, :placeholder => "Last Name" %><br>
    <%= f.email_field :email, :placeholder => "Email" %><br>
    <%= f.date_field :dob, :placeholder => "Date of Birth",:required => true %>
    <%= f.password_field :password, :placeholder => "Password", :required => true %><br>
    <%= f.password_field :password_confirmation, :placeholder => "Confirm Password", :required => true %><br>
    <%= f.submit "Submit", :class => "btn btn-primary btn-block btn-lg" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<!-- <%#= link_to root_path %> -->
<!--
#  firstname       :string
#  lastname        :string
#  email           :text
#  dob             :date
#  image           :text
#  password_digest :text -->
<div class="modal-body row">
<%if is_admin? && @user.doctor?%>
  <h1>Edit Doctor Profile</h1>
  <%= render :partial => 'doctor_form' %>
<%else%>
  <h1>Edit Profile</h1>
  <%= render :partial => 'user_form' %>
</div>
<%end%>

app/views/users/index.html.erb
<div class="modal-body row text-center">
  <h1><%= "All Doctors" %></h1>
</div>
<% @doctors.each do |doctor| %>
<div class="container-fluid">
  <div class="modal-body row">
    <div class="col-md-4"><br>
      <h3><%= "Dr. #{doctor.firstname} #{doctor.lastname}" %></h3>
      <%= cl_image_tag( doctor.image, :width => 100, :height => 150, :crop => :fill)%>
      <div class="doctor-actions" role="group" aria-label="...">
        <%if is_admin?%>
          <td>
            <%= link_to edit_user_path(doctor), class: 'btn btn-default btn-sm' do %>
              <span class="glyphicon glyphicon-pencil"></span> Edit
            <% end %>
          </td>
          <td>
            <%= link_to user_path(doctor), method: :delete, class: 'btn btn-default btn-sm', data: {confirm: "Are you sure?"} do %>
              <span class="glyphicon glyphicon-trash"></span> Delete
            <% end %>
          </td>
        <% end %>
        <td>
          <%= link_to user_path(doctor), class: 'btn btn-default btn-sm' do %>
            <span class="glyphicon glyphicon-envelope"></span> Connect
          <% end %>
        </td>
        <br>
      </div>
    </div>
    <div class="col-md-6">
      <ul class="list-group">
        <li class="list-group-item transparent">Qualifications: <%= doctor.doctor_qualifications%> </li>
        <li class="list-group-item transparent">Speciality: <%= doctor.doctor_speciality%> </li>
        <li class="list-group-item transparent">Awards/Recognitions: <%= doctor.doctor_awards_recognitions%> </li>
        <li class="list-group-item transparent">Professional Experience: <%= doctor.doctor_professional_experience%> </li>
        <li class="list-group-item transparent">Publications: <%= doctor.doctor_publications%> </li>
        <li class="list-group-item transparent">Memberships: <%= doctor.doctor_memberships%> </li>
      </ul>
    </div>
  </div>
  <div class="row"></div>
</div>
<% end %>

app/views/users/new.html.erb
<div class="modal-body row">
  <%if is_admin? %>
    <h1>Create Doctor Profile</h1><br>
    <%= render :partial => 'doctor_form' %>
  <%else%>
    <h1>New User Profile</h1><br>
    <%= render :partial => 'user_form' %>
  <%end%>
</div>

app/views/users/show.html.erb
<!-- #  username        :string
#  firstname       :string
#  lastname        :string
#  email           :text
#  dob             :date
#  image           :text
#  password_digest :text -->

<div class="container-fluid">
  <div class="modal-body">
  <%if @user.doctor?%>
    <div class="row">
      <div class="modal-body row col-md-offset-3 col-md-6 text-center"><br>
        <h1><%= "Dr. #{@user.firstname} #{@user.lastname}" %></h1>
        <%= cl_image_tag( @user.image, :width => 100, :height => 150, :crop => :fill)%>
        <ul class="list-group">
          <li class="list-group-item transparent">Qualifications: <%= @user.doctor_qualifications%> </li>
          <li class="list-group-item transparent">Speciality: <%= @user.doctor_speciality%> </li>
          <li class="list-group-item transparent">Awards/Recognitions: <%= @user.doctor_awards_recognitions%> </li>
          <li class="list-group-item transparent">Professional Experience: <%= @user.doctor_professional_experience%> </li>
          <li class="list-group-item transparent">Publications: <%= @user.doctor_publications%> </li>
          <li class="list-group-item transparent">Memberships: <%= @user.doctor_memberships%> </li>
        </ul>
        <div class="doctor-actions">
          <%if !is_doctor?%>
            <% if @is_charged %>
              <td>
                <%= link_to conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: 'post' , class: 'btn btn-default btn-sm' do %>
                  <span class="glyphicon glyphicon-envelope"></span> Message
                <% end %>
              </td>
            <%else%>
              <td>
                <%= link_to new_charge_path(doctor_id: @user.id), class: 'btn btn-default btn-sm' do %>
                  <span class="glyphicon glyphicon-send"></span> Payment
                <% end %>
              </td>
            <%end%>
            <%else%>
            <div class="container-fluid">
              <div class="modal-body">
                <div class="row">
                  <div class="modal-body row col-md-offset-3 col-md-6 text-center"><br>
                    <h1> Ongoing Consultations</h1>
                  </div>
                  <div class="col-md-offset-3 col-md-6 text-center"><br>
                    <div class="btn-group-vertical center-block" role="group" aria-label="...">
                      <% @conversations.each do |conversation| %>
                        <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
                          <% if conversation.sender_id == current_user.id %>
                            <% recipient = User.find(conversation.recipient_id) %>
                          <% else %>
                            <% recipient = User.find(conversation.sender_id) %>
                          <% end %>
                          <td>
                            <%= link_to conversation_messages_path(conversation), class: 'btn btn-primary btn-large' do %>
                              <%if current_user.doctor?%>
                                <span class="glyphicon glyphicon-envelope"></span><%=" #{recipient.firstname.capitalize}"%>
                              <%else%>
                                <span class="glyphicon glyphicon-envelope"></span><%=" Dr. #{recipient.firstname.capitalize}"%>
                              <%end%>
                            <% end %>
                          </td><br>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <%end%>
      </div>
      </div>
  </div>
  <%else%>
    <div class="modal-body row col-md-offset-4 col-md-4 text-center"><br>
      <h1><%= "#{@user.firstname.capitalize} #{@user.lastname.capitalize}" %></h1><br>
      <ul class="list-group">
        <li class="list-group-item transparent">First Name: <%= @user.firstname %></li>
        <li class="list-group-item transparent">Last Name: <%= @user.lastname %></li>
        <li class="list-group-item transparent">Email : <%= @user.email %></li>
        <li class="list-group-item transparent">Date of birth: <%= @user.dob%></li>
        <li class="list-group-item transparent">Age : <%= ((Date.today - @user.dob).to_i / 365.25).ceil %> Years</li>
      </ul>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="modal-body">
    <div class="row">
      <div class="modal-body row col-md-offset-3 col-md-6 text-center"><br>
        <h1> Ongoing Consultations</h1>
      </div>
      <div class="col-md-offset-3 col-md-6 text-center"><br>
        <div class="btn-group-vertical center-block" role="group" aria-label="...">
          <% @conversations.each do |conversation| %>
            <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
              <% if conversation.sender_id == current_user.id %>
                <% recipient = User.find(conversation.recipient_id) %>
              <% else %>
                <% recipient = User.find(conversation.sender_id) %>
              <% end %>
              <td>
                <%= link_to conversation_messages_path(conversation), class: 'btn btn-primary btn-large' do %>
                  <%if current_user.doctor?%>
                    <span class="glyphicon glyphicon-envelope"></span><%=" #{recipient.firstname.capitalize}"%>
                  <%else%>
                    <span class="glyphicon glyphicon-envelope"></span><%=" Dr. #{recipient.firstname.capitalize}"%>
                  <%end%>
                <% end %>
              </td><br>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<%end%>