config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'

  resources :charges
  resources :users
  resources :conversations do
  resources :messages
  end

  get '/login'      => 'session#new', :as => "login"
  post '/login'     => 'session#create'
  delete '/logout'  => 'session#destroy', :as => "logout"

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsed-navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if current_page?(root_path)%>
        <a class="navbar-brand">Second Opinion</a>
      <%else%>
        <a class="navbar-brand" href="/">
          <img class="img-responsive brand-img" alt="Brand" src="http://res.cloudinary.com/dbgvixfy4/image/upload/v1476756876/medical-icon-vector_sfljhj.png">
        </a>
      <%end%>
    </div>
    <div class="collapse navbar-collapse" id="collapsed-navbar">
      <% if logged_in? && !is_doctor? && current_page?(users_path) %>
        <form class="nav navbar-form navbar-left" role="search">
        <div class="input-group">
          <%= form_tag(users_path, :doctor=>true, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Specialist", class: "form-control" %>
          <% end %>
          <span class="input-group-btn">
            <button type="submit" <%= submit_tag "Search", class: "btn btn-primary"%>Search</button>
          </span>
        </div>
      </form>
    <% end %>
      <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%="#{current_user.firstname.capitalize}"%>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
          </a>
          <ul class="dropdown-menu">
            <% if is_admin? %>
              <li><%= link_to 'New Doctor', new_user_path %></li>
            <%end%>
            <% if !is_doctor? %>
              <li><%= link_to "All Doctors", users_path %></li>
              <li role="separator" class="divider"></li>
            <% end %>
            <li><%= link_to "View Mailbox", conversations_path%></li>
            <li><%= link_to "View Profile", user_path(current_user) %></li>
            <%if !is_doctor?%>
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
            <%end%>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          </ul>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", new_user_path %></li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SecondOpinionApp</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= cloudinary_js_config %>
  </head>

  <body class='<%=controller_name%> <%=action_name %>'>
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->
    <%= render :partial => './layouts/navigation' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

  <%= yield %>
  </body>

</html>